"""
Django settings for project1 project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
UPSTASH_REDIS_URL = os.getenv('UPSTASH_REDIS_URL', 'redis://localhost:6379')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=nfnb_)5h8hyk53#$_u!a(w$qg2(_$b^rjhg1t3afee82f=#2r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [UPSTASH_REDIS_URL],
        },
    }
}

# Celery
CELERY_BROKER_URL = UPSTASH_REDIS_URL
if CELERY_BROKER_URL and CELERY_BROKER_URL.startswith("rediss://"):
    _sep = "&" if "?" in CELERY_BROKER_URL else "?"
    CELERY_BROKER_URL += f"{_sep}ssl_cert_reqs=CERT_NONE"

CELERY_RESULT_BACKEND = CELERY_BROKER_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
# Application definition

INSTALLED_APPS = [
   'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appname',#for chat features
    'accounts',#for user authentication
    'channels',
    'coding_challenge',
    'allauth',                # ✅ REQUIRED
    'allauth.account',        # 🔥 IMPORTANT (missing → your error)
    'allauth.socialaccount',  # 🔥 IMPORTANT
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
]
SITE_ID = 1 # for django-allauth, if you are using it for authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ── allauth settings ──
ACCOUNT_LOGIN_METHODS         = {'email'}
ACCOUNT_SIGNUP_FIELDS         = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION    = 'none'   # We handle verification ourselves via Brevo
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'

# ── Social / Google OAuth ──
SOCIALACCOUNT_AUTO_SIGNUP      = True    # Skip confirm-signup page after Google login
SOCIALACCOUNT_LOGIN_ON_GET     = True    # Allow GET for social login (skip confirmation page)
SOCIALACCOUNT_EMAIL_REQUIRED   = False   # Don't block if Google doesn't return email
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_STORE_TOKENS     = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '366738655809-pvuo65g4otuvhlkiuukj5q0h8eucbvj3.apps.googleusercontent.com',
            'secret':    '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',
            'key':       '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'APP': {
            'client_id': 'Ov23linFdeZUXNqKAjcu',
            'secret': '8d02d19c16eb5c977968e8f48c2a91f75a575df2',
        }
    }
}

LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project1.wsgi.application'

ASGI_APPLICATION = 'project1.asgi.application'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://neondb_owner:npg_8Yxez7APOCMr@ep-wandering-breeze-a1cskk2m.ap-southeast-1.aws.neon.tech/neondb?sslmode=require',
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
