# Generated by Django 6.0.1 on 2026-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
