# Generated by Django 6.0.1 on 2026-03-19 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('total_repos', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_stars_received', models.IntegerField(default=0)),
                ('total_prs_merged', models.IntegerField(default=0)),
                ('languages_used', models.JSONField(default=dict)),
                ('notable_contributions', models.JSONField(default=list)),
                ('commit_streak', models.IntegerField(default=0)),
                ('account_age_months', models.IntegerField(default=0)),
                ('commit_map', models.JSONField(default=dict)),
                ('overall_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('complexity_score', models.FloatField(default=0)),
                ('collaboration_score', models.FloatField(default=0)),
                ('diversity_score', models.FloatField(default=0)),
                ('documentation_score', models.FloatField(default=0)),
                ('oss_contribution_score', models.FloatField(default=0)),
                ('rank_title', models.CharField(default='Unranked', max_length=50)),
                ('global_rank', models.IntegerField(default=0)),
                ('campus_rank', models.IntegerField(default=0)),
                ('top_strength', models.CharField(blank=True, max_length=100)),
                ('top_weakness', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('badges', models.JSONField(default=list)),
                ('spam_ratio', models.FloatField(default=0)),
                ('commits_per_day', models.FloatField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('cheat_flags', models.JSONField(default=list)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching GitHub Data'), ('analyzing', 'Analyzing with AI'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
    ]
