# Generated by Django 6.0.3 on 2026-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_developerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='recent_projects',
            field=models.JSONField(default=list),
        ),
    ]
