# Generated by Django 6.0.1 on 2026-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_developerprofile_recent_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_club_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
