# Generated by Django 6.0.3 on 2026-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('placement', 'Placement Drive')], default='general', max_length=20),
        ),
    ]
